# Generated by Django 3.1 on 2021-09-22 03:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='breed')),
                ('picture', models.URLField(blank=True, verbose_name='dog photo')),
                ('sub_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.breed')),
            ],
        ),
    ]
