# Generated by Django 3.1 on 2021-09-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='picture',
            new_name='img_url',
        ),
    ]
