# Generated by Django 3.1 on 2021-09-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20210922_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='sub_breed',
            new_name='parent',
        ),
    ]
