# Generated by Django 3.1 on 2021-09-22 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20210922_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.breed'),
        ),
    ]
