# Generated by Django 3.1.13 on 2021-09-23 05:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20210922_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streakvalue', models.IntegerField(default=0, verbose_name='streak')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pets.pet')),
            ],
        ),
    ]
