# Generated by Django 3.1.13 on 2021-09-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20210923_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='pets.pet'),
        ),
    ]
