# Generated by Django 3.1.13 on 2021-09-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20210923_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='pets.breed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='streak',
            name='streakvalue',
            field=models.IntegerField(default=0, verbose_name='streak count'),
        ),
    ]
