# Generated by Django 3.1.13 on 2021-09-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20210923_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pat',
            new_name='breed',
        ),
    ]
