# Generated by Django 3.1.13 on 2021-09-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_auto_20210923_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streak',
            old_name='streak_count',
            new_name='streak_value',
        ),
    ]
