# Generated by Django 3.1.13 on 2021-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_auto_20210923_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img_url',
            field=models.URLField(blank=True, verbose_name='task icon'),
        ),
    ]
