# Generated by Django 3.1.13 on 2021-09-23 17:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_auto_20210923_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='journey',
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='pets.journey')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='pets.unit'),
            preserve_default=False,
        ),
    ]
