# Generated by Django 3.1.13 on 2021-09-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_auto_20210923_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='journey',
        ),
        migrations.AddField(
            model_name='assesment',
            name='pet',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='pets.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='current_unit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journey',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey_pet', to='pets.pet'),
        ),
    ]
