# Generated by Django 3.1.13 on 2021-09-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_auto_20210923_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='task',
        ),
        migrations.DeleteModel(
            name='Assesment',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
