# Generated by Django 3.1.13 on 2021-09-23 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('pets', '0016_auto_20210923_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=False)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='pets.pet')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesment', to='units.task')),
            ],
        ),
    ]
