# Generated by Django 3.1.13 on 2021-10-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_task_instructions'),
        ('pets', '0017_assesment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='units.task'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='pets.pet'),
        ),
    ]
