# Generated by Django 3.1.13 on 2021-10-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_auto_20211001_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='current_unit',
            new_name='unit',
        ),
    ]
