# Generated by Django 3.1.13 on 2021-10-05 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_auto_20211001_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pets.pet'),
        ),
    ]
