# Generated by Django 3.1.13 on 2021-10-05 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_auto_20211005_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
