# Generated by Django 3.1.13 on 2021-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='icon_url',
            field=models.URLField(blank=True, verbose_name='task icon'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img_url',
            field=models.URLField(blank=True, verbose_name='task image'),
        ),
    ]
