# Generated by Django 3.1.13 on 2021-09-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20210923_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='instructions',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
