# Generated by Django 3.1.13 on 2021-10-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_task_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['unit__order', 'order']},
        ),
    ]
